spring.application.name=evjf-back

spring.datasource.url=jdbc:mariadb://localhost:3307/evjf
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/evjf/api
server.port=8080

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true