-- =============================================
-- EVJF - data.sql
-- Insertion des jeux et cartes
-- =============================================

-- =============================================
-- JEUX
-- =============================================
INSERT INTO game (name, description, number_round, number_questions_by_round) VALUES
('Quiz sur la mariée',      'Qui connaît le mieux la future mariée ?',                          3, 10),
('C''est qui ?',             'Devinettes sur les participantes — sauras-tu qui se cache derrière ?', 3, 10),
('Casserole Karaoké',       'Chante la chanson imposée... même si tu ne connais pas les paroles !', 1, 10),
('Mimatic',                 'Fais deviner le mot ou la situation sans parler !',                 3, 10),
('Estimation & Classement', 'Répondez, puis mettez-vous dans le bon ordre !',                   3, 10),
('10 mais…',                'La carte vaut 10 points, mais il y a un mais...',                  3, 10),
('Danse comme si',          'Danse comme si tu étais... le personnage de la carte !',            3, 10);

-- =============================================
-- CARTES — JEU 1 : Quiz sur la mariée
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Quel est son péché mignon alimentaire ?', 10, 'SOFT', 1),
('Quelle est sa série préférée du moment ?', 10, 'SOFT', 1),
('Comment s''appelle son futur mari ?', 10, 'SOFT', 1),
('Où ont-ils fêté leur premier anniversaire ?', 20, 'NORMAL', 1),
('Quelle est sa plus grande peur ?', 10, 'SOFT', 1),
('Quel est son film préféré ?', 10, 'SOFT', 1),
('Quel est son animal préféré ?', 10, 'SOFT', 1),
('Quelle est sa boisson préférée en soirée ?', 10, 'SOFT', 1),
('Dans quelle ville rêve-t-elle de vivre ?', 20, 'NORMAL', 1),
('Combien de fois a-t-elle revu sa série préférée ?', 20, 'NORMAL', 1),
('Quel est son style de musique préféré ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle déteste faire à la maison ?', 10, 'SOFT', 1),
('Quel est son plat préféré ?', 10, 'SOFT', 1),
('Comment a-t-elle rencontré son futur mari ?', 20, 'NORMAL', 1),
('Quelle est sa couleur préférée ?', 10, 'SOFT', 1),
('Quel est son pire défaut selon elle ?', 20, 'NORMAL', 1),
('Quelle est sa meilleure qualité selon elle ?', 20, 'NORMAL', 1),
('Quelle est la chose la plus folle qu''elle ait faite ?', 30, 'HARD', 1),
('Quel est son emoji le plus utilisé ?', 10, 'SOFT', 1),
('Combien de relations sérieuses a-t-elle eues avant lui ?', 30, 'HARD', 1),
('Quel est son signe astrologique ?', 10, 'SOFT', 1),
('Quelle est sa destination de voyage de rêve ?', 10, 'SOFT', 1),
('Quel est son application la plus utilisée sur son téléphone ?', 20, 'NORMAL', 1),
('Comment a-t-il fait sa demande en mariage ?', 20, 'NORMAL', 1),
('Quelle est sa chanson de mariage idéale ?', 20, 'NORMAL', 1),
('Quel est son sport préféré ou qu''elle aimerait pratiquer ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle ne supportera jamais de son mari ?', 30, 'HARD', 1),
('Combien d''enfants souhaite-t-elle avoir ?', 20, 'NORMAL', 1),
('Quel était son surnom d''enfance ?', 20, 'NORMAL', 1),
('Quelle est la première chose qu''elle remarque chez un inconnu ?', 20, 'NORMAL', 1),
('Quel est son acteur préféré ?', 10, 'SOFT', 1),
('Quelle est son actrice préférée ?', 10, 'SOFT', 1),
('Quel est son cocktail préféré ?', 10, 'SOFT', 1),
('Quelle est sa pire habitude ?', 20, 'NORMAL', 1),
('Quelle est son heure de réveil idéale le weekend ?', 10, 'SOFT', 1),
('Quel est son mot préféré ?', 20, 'NORMAL', 1),
('Quelle est la chose qu''elle achèterait en premier si elle gagnait au loto ?', 20, 'NORMAL', 1),
('Quel est son plus beau souvenir de voyage ?', 20, 'NORMAL', 1),
('Quelle est la qualité qu''elle préfère chez son futur mari ?', 20, 'NORMAL', 1),
('Quel est son défaut qu''elle tolère chez son futur mari ?', 30, 'HARD', 1),
('Quel est son parfum préféré ?', 10, 'SOFT', 1),
('Quelle est sa marque de vêtements préférée ?', 10, 'SOFT', 1),
('Quelle est sa plus grande honte ?', 30, 'HARD', 1),
('Quel métier aurait-elle voulu faire enfant ?', 20, 'NORMAL', 1),
('Quel est son livre préféré ?', 10, 'SOFT', 1),
('Quelle est sa phrase préférée ?', 20, 'NORMAL', 1),
('Qu''est-ce qu''elle ne peut pas faire sans son téléphone ?', 10, 'SOFT', 1),
('Quelle est sa tradition préférée dans sa famille ?', 20, 'NORMAL', 1),
('Quel est le dernier mensonge qu''elle a dit ?', 30, 'HARD', 1),
('Quel est son rêve le plus récurrent ?', 20, 'NORMAL', 1),
('Quel est son talent caché ?', 20, 'NORMAL', 1),
('Quelle est sa plus grande fierté ?', 20, 'NORMAL', 1),
('Quel est le cadeau le plus nul qu''elle ait reçu ?', 20, 'NORMAL', 1),
('Quel est le cadeau le plus beau qu''elle ait reçu ?', 20, 'NORMAL', 1),
('Quelle est sa pire date romantique ?', 30, 'HARD', 1),
('Comment réagit-elle quand elle est jalouse ?', 30, 'HARD', 1),
('Quelle est la chose qu''elle ferait si elle n''avait pas peur du jugement ?', 30, 'HARD', 1),
('Quel est son personnage de dessin animé préféré ?', 10, 'SOFT', 1),
('Quelle est sa saison préférée ?', 10, 'SOFT', 1),
('Quel est son plat qu''elle est incapable de cuisiner ?', 20, 'NORMAL', 1),
('Combien de paires de chaussures possède-t-elle environ ?', 20, 'NORMAL', 1),
('Quel est son rituel beauté indispensable ?', 20, 'NORMAL', 1),
('Quelle est la chose qu''elle a toujours voulu apprendre ?', 20, 'NORMAL', 1),
('Quel est son film qui la fait pleurer à chaque fois ?', 20, 'NORMAL', 1),
('Quelle est sa phobie la plus irrationnelle ?', 20, 'NORMAL', 1),
('Quel est son style de mariage de rêve ?', 20, 'NORMAL', 1),
('Quel est son moment préféré de la journée ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle ferait sans hésiter si elle était invisible ?', 30, 'HARD', 1),
('Quel est son groupe de musique préféré ?', 10, 'SOFT', 1),
('Quelle est sa plus grande addiction ?', 20, 'NORMAL', 1),
('Quel est son plaisir coupable en matière de nourriture ?', 20, 'NORMAL', 1),
('Quel est son dessert préféré ?', 10, 'SOFT', 1),
('Quelle est la dernière fois qu''elle a pleuré ?', 30, 'HARD', 1),
('Quel est son sport qu''elle regarde à la télé ?', 10, 'SOFT', 1),
('Quelle est sa chose préférée dans le mariage ?', 20, 'NORMAL', 1),
('Quel est le pays qu''elle a le plus envie de visiter ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle fait dès qu''elle arrive chez elle ?', 10, 'SOFT', 1),
('Quel est son mantra de vie ?', 20, 'NORMAL', 1),
('Quelle est la chose qui la rend immédiatement de bonne humeur ?', 20, 'NORMAL', 1),
('Quel est le truc le plus bizarre qu''elle collectionne ?', 20, 'NORMAL', 1),
('Quelle est sa chanson karaoké signature ?', 20, 'NORMAL', 1),
('Quel est son type de pizza préféré ?', 10, 'SOFT', 1),
('Quelle est sa phrase quand elle est énervée ?', 30, 'HARD', 1),
('Quel est son surnom donné par son futur mari ?', 20, 'NORMAL', 1),
('Quel est le surnom qu''elle donne à son futur mari ?', 20, 'NORMAL', 1),
('Quelle est la chose la plus romantique qu''il ait faite pour elle ?', 20, 'NORMAL', 1),
('Quel est son type de vacances idéales ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle regrette le plus dans sa vie ?', 30, 'HARD', 1),
('Quel est son souvenir d''enfance préféré ?', 20, 'NORMAL', 1),
('Quelle est sa playlist de sport ?', 10, 'SOFT', 1),
('Quel est le plat qu''elle cuisine le mieux ?', 20, 'NORMAL', 1),
('Quelle est la chose qu''elle ne peut pas s''empêcher d''acheter ?', 20, 'NORMAL', 1),
('Quel est son style déco préféré ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle ferait différemment si elle pouvait revenir en arrière ?', 30, 'HARD', 1),
('Quel est son type de garçon avant son futur mari ?', 30, 'HARD', 1),
('Quelle est la chose qui la ferait fuir d''une soirée ?', 20, 'NORMAL', 1),
('Quel est son signe chinois ?', 10, 'SOFT', 1),
('Quelle est la chose qu''elle a promis de ne plus jamais faire ?', 30, 'HARD', 1);

-- =============================================
-- CARTES — JEU 2 : C'est qui ?
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Elle est toujours la dernière prête mais la première à presser les autres', 20, 'NORMAL', 2),
('Elle pleure à tous les films même les plus nuls', 20, 'NORMAL', 2),
('Elle a toujours un chewing-gum sur elle', 10, 'SOFT', 2),
('Elle est incapable de garder un secret plus de 24h', 30, 'HARD', 2),
('Elle commande toujours la même chose au restaurant', 10, 'SOFT', 2),
('Elle prend 47 photos avant d''en poster une', 20, 'NORMAL', 2),
('Elle arrive toujours en retard mais avec une excuse béton', 20, 'NORMAL', 2),
('Elle mange les frites des autres sans demander', 10, 'SOFT', 2),
('Elle dit toujours "je suis au régime" et commande un dessert', 20, 'NORMAL', 2),
('Elle est la première à danser et la dernière à s''arrêter', 20, 'NORMAL', 2),
('Elle connaît les paroles de toutes les chansons des années 2000', 10, 'SOFT', 2),
('Elle est obsédée par son horoscope', 20, 'NORMAL', 2),
('Elle ne supporte pas le silence dans une voiture', 10, 'SOFT', 2),
('Elle fait semblant de dormir pour éviter les conversations', 30, 'HARD', 2),
('Elle est toujours la première à liker vos posts', 10, 'SOFT', 2),
('Elle texte encore son ex de temps en temps', 30, 'HARD', 2),
('Elle est incapable de commander sans poser 12 questions au serveur', 20, 'NORMAL', 2),
('Elle pleure quand elle boit trop', 30, 'HARD', 2),
('Elle est celle qui ramasse tout le monde en taxi à 3h du mat', 10, 'SOFT', 2),
('Elle a peur de vieillir et le dit tout le temps', 20, 'NORMAL', 2),
('Elle est celle qui chante faux mais avec le plus d''enthousiasme', 20, 'NORMAL', 2),
('Elle est toujours en train de documenter sa vie en stories', 20, 'NORMAL', 2),
('Elle refuse de sortir sans son mascara', 10, 'SOFT', 2),
('Elle est celle qui propose toujours un dernier verre', 20, 'NORMAL', 2),
('Elle est celle qui donne des conseils non sollicités', 30, 'HARD', 2),
('Elle est celle qui organise tout à la dernière minute', 20, 'NORMAL', 2),
('Elle est celle qui dort avec 47 coussins', 10, 'SOFT', 2),
('Elle est celle qui a toujours froid partout', 10, 'SOFT', 2),
('Elle est celle qui parle à ses plantes', 20, 'NORMAL', 2),
('Elle est celle qui fait des listes pour tout', 20, 'NORMAL', 2),
('Elle est celle qui ne peut pas s''endormir sans regarder son téléphone', 10, 'SOFT', 2),
('Elle est celle qui pleure dans les pubs de Noël', 20, 'NORMAL', 2),
('Elle est celle qui parle aux animaux inconnus dans la rue', 10, 'SOFT', 2),
('Elle est celle qui connaît tous les potins du groupe avant tout le monde', 30, 'HARD', 2),
('Elle est celle qui commande toujours pour la table', 20, 'NORMAL', 2),
('Elle est celle qui prend une heure à dire au revoir', 10, 'SOFT', 2),
('Elle est celle qui snapchat ses repas avant de manger', 10, 'SOFT', 2),
('Elle est celle qui relit ses messages 10 fois avant d''envoyer', 20, 'NORMAL', 2),
('Elle est celle qui met des rappels pour tout', 10, 'SOFT', 2),
('Elle est celle qui choisit toujours le restaurant le plus cher', 20, 'NORMAL', 2),
('Elle est celle qui répond toujours en vocal', 10, 'SOFT', 2),
('Elle est celle qui oublie toujours son téléphone quelque part', 20, 'NORMAL', 2),
('Elle est celle qui pleure quand elle est fatiguée', 30, 'HARD', 2),
('Elle est celle qui parle le plus fort sans s''en rendre compte', 20, 'NORMAL', 2),
('Elle est celle qui achète des trucs inutiles dans les magasins de déco', 10, 'SOFT', 2),
('Elle est celle qui zappe toujours au meilleur moment du film', 20, 'NORMAL', 2),
('Elle est celle qui arrive avec 10 valises pour un weekend', 20, 'NORMAL', 2),
('Elle est celle qui change d''avis au dernier moment', 30, 'HARD', 2),
('Elle est celle qui démarre Netflix sans attendre les autres', 20, 'NORMAL', 2),
('Elle est celle qui dit "j''arrive dans 5 min" mais met 30 min', 20, 'NORMAL', 2),
('Elle est celle qui rit à ses propres blagues', 10, 'SOFT', 2),
('Elle est celle qui donne des surnoms à tout le monde', 10, 'SOFT', 2),
('Elle est celle qui veut toujours faire des activités', 20, 'NORMAL', 2),
('Elle est celle qui dort n''importe où n''importe quand', 10, 'SOFT', 2),
('Elle est celle qui garde tous les tickets et emballages', 30, 'HARD', 2),
('Elle est celle qui connaît les anecdotes de tout le monde', 30, 'HARD', 2),
('Elle est celle qui danse même sans musique', 10, 'SOFT', 2),
('Elle est celle qui fait des vocaux de 4 minutes', 20, 'NORMAL', 2),
('Elle est celle qui aime tout arranger entre les gens', 30, 'HARD', 2),
('Elle est celle qui achète des vêtements et ne les porte jamais', 20, 'NORMAL', 2),
('Elle est celle qui connaît par cœur les menus de tous les restos du quartier', 10, 'SOFT', 2),
('Elle est celle qui commence les phrases et ne les finit pas', 20, 'NORMAL', 2),
('Elle est celle qui fait confiance aux inconnus trop vite', 30, 'HARD', 2),
('Elle est celle qui est accro aux séries coréennes', 20, 'NORMAL', 2),
('Elle est celle qui range tout au millimètre près', 20, 'NORMAL', 2),
('Elle est celle qui perd ses clés une fois par semaine', 10, 'SOFT', 2),
('Elle est celle qui a toujours un doliprane sur elle', 10, 'SOFT', 2),
('Elle est celle qui commande des trucs sur internet à 2h du matin', 30, 'HARD', 2),
('Elle est celle qui prend le plus de place dans le lit en week-end à l''hôtel', 20, 'NORMAL', 2),
('Elle est celle qui chante sous la douche', 10, 'SOFT', 2),
('Elle est celle qui parle de son régime tout en mangeant un burger', 20, 'NORMAL', 2),
('Elle est celle qui collectionne les bougies mais ne les allume jamais', 20, 'NORMAL', 2),
('Elle est celle qui dit "non" aux plans mais vient quand même', 20, 'NORMAL', 2),
('Elle est celle qui pleure en regardant des vidéos de chiens', 10, 'SOFT', 2),
('Elle est celle qui est toujours partante pour un dernier shot', 30, 'HARD', 2),
('Elle est celle qui met des alertes pour les ventes privées', 20, 'NORMAL', 2),
('Elle est celle qui envoie des memes à 7h du matin', 10, 'SOFT', 2),
('Elle est celle qui hésite une éternité devant le menu', 20, 'NORMAL', 2),
('Elle est celle qui écrit de longs messages pour rien', 10, 'SOFT', 2),
('Elle est celle qui range ses affaires en faisant ses valises 3 jours avant', 20, 'NORMAL', 2),
('Elle est celle qui répond "oui" aux plans et ne vient pas', 30, 'HARD', 2),
('Elle est celle qui a du mal à lâcher son téléphone en soirée', 20, 'NORMAL', 2),
('Elle est celle qui connaît les noms de tous les ex du groupe', 30, 'HARD', 2),
('Elle est celle qui organise les photos de groupe', 10, 'SOFT', 2),
('Elle est celle qui remonte le moral de tout le monde', 10, 'SOFT', 2),
('Elle est celle qui cuisine pour 20 personnes pour 4', 20, 'NORMAL', 2),
('Elle est celle qui choisit toujours la playlist en voiture', 20, 'NORMAL', 2),
('Elle est celle qui n''a jamais froid dehors même en hiver', 20, 'NORMAL', 2),
('Elle est celle qui adopte les habitudes de ses copines', 20, 'NORMAL', 2),
('Elle est celle qui parle encore de son voyage d''il y a 5 ans', 20, 'NORMAL', 2),
('Elle est celle qui fait des cadeaux trop bien emballés', 10, 'SOFT', 2),
('Elle est celle qui arrive toujours la première à une soirée', 10, 'SOFT', 2),
('Elle est celle qui a des avis sur tout', 30, 'HARD', 2),
('Elle est celle qui sait toujours quoi dire quand ça va pas', 20, 'NORMAL', 2),
('Elle est celle qui photographie ses pieds sur la plage', 10, 'SOFT', 2),
('Elle est celle qui fait des siestes de 10 min qui durent 2h', 20, 'NORMAL', 2),
('Elle est celle qui ajoute tout le monde sur LinkedIn', 10, 'SOFT', 2),
('Elle est celle qui fait des listes de films à voir et ne les regarde jamais', 20, 'NORMAL', 2),
('Elle est celle qui envoie des confettis dans les conversations de groupe', 10, 'SOFT', 2);

-- =============================================
-- CARTES — JEU 3 : Casserole Karaoké
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Billie Jean — Michael Jackson', 20, 'NORMAL', 3),
('All I Want for Christmas Is You — Mariah Carey', 10, 'SOFT', 3),
('Bohemian Rhapsody — Queen', 30, 'HARD', 3),
('Baby One More Time — Britney Spears', 10, 'SOFT', 3),
('Rolling in the Deep — Adele', 20, 'NORMAL', 3),
('Wannabe — Spice Girls', 10, 'SOFT', 3),
('Toxic — Britney Spears', 20, 'NORMAL', 3),
('Single Ladies — Beyoncé', 20, 'NORMAL', 3),
('Thriller — Michael Jackson', 30, 'HARD', 3),
('Shape of You — Ed Sheeran', 10, 'SOFT', 3),
('Uptown Funk — Bruno Mars', 20, 'NORMAL', 3),
('Happy — Pharrell Williams', 10, 'SOFT', 3),
('Thinking Out Loud — Ed Sheeran', 20, 'NORMAL', 3),
('Shake It Off — Taylor Swift', 10, 'SOFT', 3),
('Bad Romance — Lady Gaga', 20, 'NORMAL', 3),
('Someone Like You — Adele', 20, 'NORMAL', 3),
('Poker Face — Lady Gaga', 20, 'NORMAL', 3),
('Just Dance — Lady Gaga', 10, 'SOFT', 3),
('Hips Don''t Lie — Shakira', 20, 'NORMAL', 3),
('Waka Waka — Shakira', 10, 'SOFT', 3),
('Can''t Stop the Feeling — Justin Timberlake', 10, 'SOFT', 3),
('Senorita — Shawn Mendes & Camila Cabello', 20, 'NORMAL', 3),
('Despacito — Luis Fonsi', 20, 'NORMAL', 3),
('Blinding Lights — The Weeknd', 20, 'NORMAL', 3),
('Old Town Road — Lil Nas X', 10, 'SOFT', 3),
('Levitating — Dua Lipa', 10, 'SOFT', 3),
('Don''t Start Now — Dua Lipa', 20, 'NORMAL', 3),
('Physical — Dua Lipa', 20, 'NORMAL', 3),
('Watermelon Sugar — Harry Styles', 10, 'SOFT', 3),
('As It Was — Harry Styles', 10, 'SOFT', 3),
('Heat Waves — Glass Animals', 20, 'NORMAL', 3),
('Stay — The Kid LAROI & Justin Bieber', 10, 'SOFT', 3),
('Good 4 U — Olivia Rodrigo', 20, 'NORMAL', 3),
('Drivers License — Olivia Rodrigo', 20, 'NORMAL', 3),
('Dynamite — BTS', 20, 'NORMAL', 3),
('Permission to Dance — BTS', 10, 'SOFT', 3),
('Butter — BTS', 10, 'SOFT', 3),
('Smooth Criminal — Michael Jackson', 30, 'HARD', 3),
('Don''t Stop Me Now — Queen', 30, 'HARD', 3),
('We Will Rock You — Queen', 10, 'SOFT', 3),
('Africa — Toto', 30, 'HARD', 3),
('Take On Me — A-ha', 30, 'HARD', 3),
('Girls Just Want to Have Fun — Cyndi Lauper', 10, 'SOFT', 3),
('I Will Survive — Gloria Gaynor', 20, 'NORMAL', 3),
('Material Girl — Madonna', 20, 'NORMAL', 3),
('Like a Prayer — Madonna', 30, 'HARD', 3),
('Lose Yourself — Eminem', 30, 'HARD', 3),
('Without Me — Eminem', 20, 'NORMAL', 3),
('Hotline Bling — Drake', 20, 'NORMAL', 3),
('God''s Plan — Drake', 20, 'NORMAL', 3),
('Sicko Mode — Travis Scott', 30, 'HARD', 3),
('Rockstar — Post Malone', 20, 'NORMAL', 3),
('Sunflower — Post Malone', 10, 'SOFT', 3),
('Psycho — Post Malone', 20, 'NORMAL', 3),
('Sorry — Justin Bieber', 10, 'SOFT', 3),
('Love Yourself — Justin Bieber', 10, 'SOFT', 3),
('Peaches — Justin Bieber', 10, 'SOFT', 3),
('Call Me Maybe — Carly Rae Jepsen', 10, 'SOFT', 3),
('Roar — Katy Perry', 10, 'SOFT', 3),
('Firework — Katy Perry', 10, 'SOFT', 3),
('Dark Horse — Katy Perry', 20, 'NORMAL', 3),
('Teenage Dream — Katy Perry', 20, 'NORMAL', 3),
('Umbrella — Rihanna', 20, 'NORMAL', 3),
('We Found Love — Rihanna', 10, 'SOFT', 3),
('Diamonds — Rihanna', 10, 'SOFT', 3),
('Work — Rihanna', 20, 'NORMAL', 3),
('Chandelier — Sia', 30, 'HARD', 3),
('Cheap Thrills — Sia', 10, 'SOFT', 3),
('Elastic Heart — Sia', 30, 'HARD', 3),
('Counting Stars — One Republic', 10, 'SOFT', 3),
('Apologize — One Republic', 20, 'NORMAL', 3),
('Radioactive — Imagine Dragons', 20, 'NORMAL', 3),
('Demons — Imagine Dragons', 20, 'NORMAL', 3),
('Thunder — Imagine Dragons', 10, 'SOFT', 3),
('Believer — Imagine Dragons', 20, 'NORMAL', 3),
('Wake Me Up — Avicii', 10, 'SOFT', 3),
('The Nights — Avicii', 20, 'NORMAL', 3),
('Lean On — Major Lazer', 10, 'SOFT', 3),
('Cheap Thrills — Sia ft. Sean Paul', 10, 'SOFT', 3),
('Closer — The Chainsmokers', 10, 'SOFT', 3),
('Don''t Let Me Down — The Chainsmokers', 20, 'NORMAL', 3),
('Something Just Like This — Coldplay & The Chainsmokers', 10, 'SOFT', 3),
('A Sky Full of Stars — Coldplay', 20, 'NORMAL', 3),
('The Scientist — Coldplay', 30, 'HARD', 3),
('Yellow — Coldplay', 20, 'NORMAL', 3),
('Fix You — Coldplay', 30, 'HARD', 3),
('Viva La Vida — Coldplay', 20, 'NORMAL', 3),
('Paradise — Coldplay', 20, 'NORMAL', 3),
('Clocks — Coldplay', 30, 'HARD', 3),
('Je veux — Zaz', 20, 'NORMAL', 3),
('La vie en rose — Édith Piaf', 20, 'NORMAL', 3),
('L''envie d''aimer — Les Dix Commandements', 20, 'NORMAL', 3),
('Alors on danse — Stromae', 20, 'NORMAL', 3),
('Formidable — Stromae', 20, 'NORMAL', 3),
('Papaoutai — Stromae', 30, 'HARD', 3),
('Tous les mêmes — Stromae', 20, 'NORMAL', 3),
('Nuit 17 à 52 — Christine and the Queens', 30, 'HARD', 3),
('Paradis — Angèle', 10, 'SOFT', 3),
('Tout oublier — Angèle ft. Roméo Elvis', 10, 'SOFT', 3);

-- =============================================
-- CARTES — JEU 4 : Mimatic
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Un flamant rose qui apprend à faire du ski', 20, 'NORMAL', 4),
('Une grand-mère qui découvre TikTok', 10, 'SOFT', 4),
('Un astronaute qui perd son casque dans l''espace', 30, 'HARD', 4),
('Un chien qui essaie de conduire une voiture', 20, 'NORMAL', 4),
('Une mariée dont la robe est trop grande', 10, 'SOFT', 4),
('Un pingouin qui fait du yoga', 20, 'NORMAL', 4),
('Un chef cuisinier qui a peur du feu', 30, 'HARD', 4),
('Un robot qui apprend à danser la salsa', 20, 'NORMAL', 4),
('Un plongeur qui découvre qu''il a peur de l''eau', 30, 'HARD', 4),
('Une sirène qui essaie de marcher pour la première fois', 20, 'NORMAL', 4),
('Un cowboy qui a le vertige sur son cheval', 20, 'NORMAL', 4),
('Un mime pris dans une tempête de vent', 20, 'NORMAL', 4),
('Un vampire allergique à l''ail qui fait la cuisine', 30, 'HARD', 4),
('Un superhéros qui a peur des araignées', 20, 'NORMAL', 4),
('Une princesse qui répare sa voiture', 20, 'NORMAL', 4),
('Un zombie qui fait du shopping', 10, 'SOFT', 4),
('Un singe qui passe un entretien d''embauche', 20, 'NORMAL', 4),
('Un fantôme qui apprend à hanter une maison moderne', 20, 'NORMAL', 4),
('Un pirate qui a le mal de mer', 30, 'HARD', 4),
('Une fée qui a perdu sa baguette magique', 20, 'NORMAL', 4),
('Un dinosaure qui essaie de rentrer dans un taxi', 10, 'SOFT', 4),
('Un mannequin qui trébuche sur un podium', 10, 'SOFT', 4),
('Un magicien dont les tours ne fonctionnent pas', 20, 'NORMAL', 4),
('Un pompier qui a peur du feu', 30, 'HARD', 4),
('Une ballerine qui a les pieds dans le plâtre', 30, 'HARD', 4),
('Un lutteur de sumo qui fait de la broderie', 20, 'NORMAL', 4),
('Un superhéros qui essaie de s''habiller en civil', 20, 'NORMAL', 4),
('Un alien qui découvre un McDonalds', 10, 'SOFT', 4),
('Un chevalier en armure qui essaie de s''asseoir', 20, 'NORMAL', 4),
('Un loup-garou qui fait une manucure', 20, 'NORMAL', 4),
('Un prof de gym de 80 ans', 10, 'SOFT', 4),
('Une star du cinéma qui fait la vaisselle', 10, 'SOFT', 4),
('Un personnage de dessin animé qui prend vie', 20, 'NORMAL', 4),
('Un détective privé qui cherche ses propres lunettes', 20, 'NORMAL', 4),
('Un manchot qui essaie de voler', 30, 'HARD', 4),
('Un roi qui fait le ménage', 10, 'SOFT', 4),
('Une star de rock qui découvre qu''il joue faux', 30, 'HARD', 4),
('Un clown triste lors d''une fête', 20, 'NORMAL', 4),
('Un chevalier Jedi qui perd son sabre laser', 30, 'HARD', 4),
('Un sosie de célébrité qui se fait reconnaître dans la rue', 20, 'NORMAL', 4),
('Un chat qui essaie de faire semblant d''être un chien', 10, 'SOFT', 4),
('Un extraterrestre qui apprend à utiliser un smartphone', 10, 'SOFT', 4),
('Un danseur de breakdance dans un costume de lapin de Pâques', 20, 'NORMAL', 4),
('Un chef étoilé qui mange un kebab', 10, 'SOFT', 4),
('Un enfant qui veut absolument paraître adulte', 10, 'SOFT', 4),
('Un robot qui essaie de ressentir des émotions', 30, 'HARD', 4),
('Un fantôme qui est allergique aux maisons hantées', 30, 'HARD', 4),
('Un surfeur qui découvre la neige', 20, 'NORMAL', 4),
('Un hipster qui découvre un fast food', 20, 'NORMAL', 4),
('Un acteur qui oublie son texte sur scène', 30, 'HARD', 4),
('Une reine d''Angleterre au McDo', 10, 'SOFT', 4),
('Un bodybuilder qui a peur des souris', 30, 'HARD', 4),
('Un astronaute qui rentre chez lui après 6 mois dans l''espace', 20, 'NORMAL', 4),
('Un dinosaure qui apprend à utiliser un téléphone', 10, 'SOFT', 4),
('Un toréador face à une vache très calme', 20, 'NORMAL', 4),
('Un ninja qui essaie d''être discret à une fête', 30, 'HARD', 4),
('Une star de cinéma qui rate son audition', 20, 'NORMAL', 4),
('Un medecin qui a peur du sang', 30, 'HARD', 4),
('Un pompier qui cherche une sortie de secours dans un labyrinthe', 20, 'NORMAL', 4),
('Un danseur classique qui fait du rap', 20, 'NORMAL', 4),
('Un Viking qui fait du shopping en galerie commerciale', 10, 'SOFT', 4),
('Un politicien qui dit la vérité pour la première fois', 30, 'HARD', 4),
('Un golfeur dans une tempête', 20, 'NORMAL', 4),
('Un livreur qui ne trouve jamais la bonne adresse', 10, 'SOFT', 4),
('Un dompteur de lions face à un chaton', 20, 'NORMAL', 4),
('Un professeur qui découvre que ses élèves savaient tout depuis le début', 30, 'HARD', 4),
('Un snowboarder sur une dune de sable', 20, 'NORMAL', 4),
('Un marathonien qui court pour attraper son bus', 10, 'SOFT', 4),
('Un directeur d''école qui fait l''appel avec une musique trap', 20, 'NORMAL', 4),
('Un plombier dans un château', 20, 'NORMAL', 4),
('Un rappeur qui chante de l''opéra', 30, 'HARD', 4),
('Un boulanger qui se réveille et réalise qu''il déteste le pain', 30, 'HARD', 4),
('Un joueur de tennis dont la raquette est trop petite', 20, 'NORMAL', 4),
('Un dentiste qui a peur des dents', 30, 'HARD', 4),
('Un cuisinier qui fait brûler de l''eau', 20, 'NORMAL', 4),
('Un cambrioleur maladroit', 20, 'NORMAL', 4),
('Un vieux sage qui n''a rien de sage à dire', 20, 'NORMAL', 4),
('Une célébrité qui fait la queue comme tout le monde', 10, 'SOFT', 4),
('Un peintre qui est daltonien', 30, 'HARD', 4),
('Un chanteur d''opéra dans une bibliothèque', 20, 'NORMAL', 4),
('Un pilote de Formule 1 dans un parking', 10, 'SOFT', 4),
('Un jongleur qui a oublié comment jongler', 30, 'HARD', 4),
('Un superhéros qui rate son atterrissage', 20, 'NORMAL', 4),
('Un maquilleur qui est épileptique', 30, 'HARD', 4),
('Un touriste perdu dans sa propre ville', 10, 'SOFT', 4),
('Un vigile qui laisse passer tout le monde', 20, 'NORMAL', 4),
('Un barman qui a le hoquet', 20, 'NORMAL', 4),
('Un cheval qui apprend à faire du vélo', 20, 'NORMAL', 4),
('Un milliardaire qui fait ses courses avec des coupons de réduction', 10, 'SOFT', 4),
('Un coach sportif complètement épuisé', 20, 'NORMAL', 4),
('Un détective qui perd toutes ses preuves', 30, 'HARD', 4),
('Un crocodile qui essaie d''être végétarien', 30, 'HARD', 4),
('Un modèle photo qui n''arrive pas à sourire naturellement', 20, 'NORMAL', 4),
('Un plongeon du 10 mètres dans une piscine vide', 30, 'HARD', 4),
('Un steward/hôtesse de l''air dans une voiture', 10, 'SOFT', 4),
('Un fakir qui a peur de la douleur', 30, 'HARD', 4),
('Un directeur artistique qui perd tout son équipement', 20, 'NORMAL', 4),
('Un agent secret dont le déguisement ne fonctionne pas', 20, 'NORMAL', 4);

-- =============================================
-- CARTES — JEU 5 : Estimation & Classement
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Combien de fois avez-vous déménagé dans votre vie ?', 10, 'SOFT', 5),
('Combien de relations amoureuses avez-vous eues ?', 30, 'HARD', 5),
('Combien d''heures dormez-vous par nuit en moyenne ?', 10, 'SOFT', 5),
('Combien de paires de chaussures possédez-vous ?', 20, 'NORMAL', 5),
('Combien de pays avez-vous visités ?', 20, 'NORMAL', 5),
('Combien de fois par semaine mangez-vous au restaurant ?', 10, 'SOFT', 5),
('Combien de selfies prenez-vous par semaine ?', 20, 'NORMAL', 5),
('Combien de fois par an pleurez-vous ?', 20, 'NORMAL', 5),
('Combien de livres lisez-vous par an ?', 10, 'SOFT', 5),
('Combien d''heures par jour passez-vous sur votre téléphone ?', 20, 'NORMAL', 5),
('Combien de personnes avez-vous déjà embrassées ?', 30, 'HARD', 5),
('Combien de fois par mois allez-vous en soirée ?', 20, 'NORMAL', 5),
('Combien de photos avez-vous dans votre téléphone ?', 20, 'NORMAL', 5),
('Combien de fois par an vous disputez-vous avec vos proches ?', 30, 'HARD', 5),
('Combien d''heures de séries regardez-vous par semaine ?', 20, 'NORMAL', 5),
('Combien de fois par mois faites-vous du sport ?', 10, 'SOFT', 5),
('Combien de cafés buvez-vous par jour ?', 10, 'SOFT', 5),
('Combien d''amis proches avez-vous vraiment ?', 20, 'NORMAL', 5),
('Combien de fois par semaine cuisinez-vous ?', 10, 'SOFT', 5),
('Combien de fois par an achetez-vous des vêtements ?', 20, 'NORMAL', 5),
('Combien de minutes prenez-vous pour vous préparer le matin ?', 20, 'NORMAL', 5),
('Combien d''applications avez-vous sur votre téléphone ?', 20, 'NORMAL', 5),
('Combien de fois par semaine vérifiez-vous vos réseaux sociaux ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous changé de travail ?', 20, 'NORMAL', 5),
('Combien de fois par mois sortez-vous boire un verre ?', 20, 'NORMAL', 5),
('Combien de fois par an faites-vous le grand ménage ?', 10, 'SOFT', 5),
('Combien d''abonnements streaming avez-vous ?', 10, 'SOFT', 5),
('Combien de groupes WhatsApp avez-vous ?', 20, 'NORMAL', 5),
('Combien de fois par an vous offrez-vous un soin ?', 20, 'NORMAL', 5),
('Combien de followers avez-vous sur Instagram ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous raté un vol ou un train ?', 20, 'NORMAL', 5),
('Combien de fois par an vous teignez-vous les cheveux ?', 20, 'NORMAL', 5),
('Combien de régimes avez-vous essayés dans votre vie ?', 20, 'NORMAL', 5),
('Combien de fois par an allez-vous chez le médecin ?', 10, 'SOFT', 5),
('Combien de fois avez-vous regardé votre série préférée ?', 30, 'HARD', 5),
('Combien d''heures dormez-vous en moyenne en weekend ?', 10, 'SOFT', 5),
('Combien de plantes avez-vous chez vous ?', 10, 'SOFT', 5),
('Combien de fois par semaine lavez-vous vos cheveux ?', 10, 'SOFT', 5),
('Combien de fois avez-vous dit "je t''aime" dans votre vie ?', 30, 'HARD', 5),
('Combien de chaussures portez-vous vraiment parmi celles que vous possédez ?', 20, 'NORMAL', 5),
('Combien de fois par an faites-vous vos valises ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous changé de coiffure cette année ?', 20, 'NORMAL', 5),
('Combien de messages envoyez-vous par jour ?', 20, 'NORMAL', 5),
('Combien d''alarmes mettez-vous le matin ?', 10, 'SOFT', 5),
('Combien d''heures par semaine regardez-vous YouTube ?', 20, 'NORMAL', 5),
('Combien de fois par mois appelez-vous votre mère ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous rompu avec quelqu''un ?', 30, 'HARD', 5),
('Combien de fois par semaine mangez-vous du sucré ?', 10, 'SOFT', 5),
('Combien de cadeaux offrez-vous en moyenne à Noël ?', 20, 'NORMAL', 5),
('Combien de fois par an vous disputez-vous avec votre meilleure amie ?', 30, 'HARD', 5),
('Combien d''heures par semaine passez-vous à vous maquiller ?', 20, 'NORMAL', 5),
('Combien de contacts avez-vous dans votre téléphone ?', 20, 'NORMAL', 5),
('Combien de fois par semaine faites-vous votre lit ?', 10, 'SOFT', 5),
('Combien de films regardez-vous par mois ?', 10, 'SOFT', 5),
('Combien de cartes de fidélité avez-vous dans votre portefeuille ?', 10, 'SOFT', 5),
('Combien de fois avez-vous eu le cœur brisé ?', 30, 'HARD', 5),
('Combien de chansons avez-vous dans votre playlist préférée ?', 20, 'NORMAL', 5),
('Combien de fois par semaine commandez-vous à manger ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous manqué un rendez-vous important ?', 30, 'HARD', 5),
('Combien de fois êtes-vous allées en festival ?', 20, 'NORMAL', 5),
('Combien de nuits blanches avez-vous faites dans votre vie ?', 30, 'HARD', 5),
('Combien de fois par an allez-vous au cinéma ?', 10, 'SOFT', 5),
('Combien de bougies avez-vous chez vous ?', 10, 'SOFT', 5),
('Combien de fois avez-vous changé de numéro de téléphone ?', 10, 'SOFT', 5),
('Combien de fois par an faites-vous du shopping en ligne ?', 20, 'NORMAL', 5),
('Combien d''exs vous suivent encore sur les réseaux ?', 30, 'HARD', 5),
('Combien de fois par semaine riez-vous à voix haute ?', 10, 'SOFT', 5),
('Combien de fois avez-vous déjà chanté sous la douche cette semaine ?', 10, 'SOFT', 5),
('Combien de fois par an faites-vous une sieste ?', 10, 'SOFT', 5),
('Combien de biographies ou de livres de développement personnel avez-vous lus ?', 20, 'NORMAL', 5),
('Combien de fois par an changez-vous votre photo de profil ?', 10, 'SOFT', 5),
('Combien de fois avez-vous essayé de méditer ?', 20, 'NORMAL', 5),
('Combien d''amis d''enfance avez-vous gardés ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous remeublé votre appartement ?', 20, 'NORMAL', 5),
('Combien de fois par an allez-vous chez le coiffeur ?', 10, 'SOFT', 5),
('Combien de fois par semaine écoutez-vous de la musique ?', 10, 'SOFT', 5),
('Combien de fois avez-vous participé à un mariage en tant qu''invitée ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous fait semblant d''être malade pour ne pas sortir ?', 30, 'HARD', 5),
('Combien de fois avez-vous essayé de cuisiner un plat et raté ?', 20, 'NORMAL', 5),
('Combien de fois par an faites-vous une bonne action ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous été en retard à un rendez-vous amoureux ?', 30, 'HARD', 5),
('Combien de fois par mois fantasmez-vous sur votre vie idéale ?', 30, 'HARD', 5),
('Combien de fois avez-vous eu un coup de foudre ?', 30, 'HARD', 5),
('Combien de fois par an rêvez-vous de tout plaquer ?', 30, 'HARD', 5),
('Combien de fois avez-vous regardé un film deux fois dans la même semaine ?', 20, 'NORMAL', 5),
('Combien de fois par an allez-vous à un concert ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous menti pour vous sortir d''une situation ?', 30, 'HARD', 5),
('Combien de fois par jour vérifiez-vous votre boîte mail ?', 10, 'SOFT', 5),
('Combien de sacs à main possédez-vous ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous commencé un journal intime ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous changé de mot de passe cette année ?', 10, 'SOFT', 5),
('Combien d''heures passez-vous à choisir quoi regarder sur Netflix ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous essayé de faire du sport et abandonné ?', 20, 'NORMAL', 5),
('Combien de fois par semaine pensez-vous à votre futur ?', 20, 'NORMAL', 5),
('Combien de fois avez-vous ri jusqu''aux larmes ce mois-ci ?', 10, 'SOFT', 5);

-- =============================================
-- CARTES — JEU 6 : 10 mais...
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Il ne t''offre jamais de cadeaux', 10, 'SOFT', 6),
('Elle pense encore à son ex', 20, 'NORMAL', 6),
('Il laisse toujours la chasse d''eau ouverte', 10, 'SOFT', 6),
('Il répond aux messages 3 jours plus tard', 20, 'NORMAL', 6),
('Elle raconte tes secrets à ses amies', 30, 'HARD', 6),
('Il ronfle comme un ours en hibernation', 20, 'NORMAL', 6),
('Elle est accro à son téléphone en soirée', 10, 'SOFT', 6),
('Il oublie systématiquement les dates importantes', 30, 'HARD', 6),
('Elle dépense son salaire le jour de la paie', 20, 'NORMAL', 6),
('Il ne range jamais ses affaires', 10, 'SOFT', 6),
('Elle critique tous tes choix vestimentaires', 30, 'HARD', 6),
('Il dit toujours qu''il n''a pas faim et mange ton assiette', 20, 'NORMAL', 6),
('Elle arrive toujours en retard', 10, 'SOFT', 6),
('Il ne fait jamais la vaisselle', 10, 'SOFT', 6),
('Elle commente toutes tes photos avec ses opinions', 20, 'NORMAL', 6),
('Il regarde des spoilers et les partage sans prévenir', 30, 'HARD', 6),
('Elle te juge quand tu manges mal', 20, 'NORMAL', 6),
('Il n''écoute jamais jusqu''au bout quand tu parles', 30, 'HARD', 6),
('Elle recommande des films qu''elle n''a pas vus', 10, 'SOFT', 6),
('Il chante faux et ne s''en rend pas compte', 10, 'SOFT', 6),
('Elle perd ses affaires tout le temps et accuse les autres', 20, 'NORMAL', 6),
('Il prend toujours la dernière part sans demander', 20, 'NORMAL', 6),
('Elle se souvient de tout ce que tu as dit il y a 5 ans', 30, 'HARD', 6),
('Il change d''avis constamment sur tout', 20, 'NORMAL', 6),
('Elle fait semblant de ne pas entendre quand ça l''arrange', 30, 'HARD', 6),
('Il ne dit jamais qu''il a tort', 30, 'HARD', 6),
('Elle squatte ton chargeur sans demander', 10, 'SOFT', 6),
('Il met la musique à fond à 8h du matin', 20, 'NORMAL', 6),
('Elle parle au téléphone en mode haut-parleur partout', 20, 'NORMAL', 6),
('Il ne range jamais le frigo dans l''ordre', 10, 'SOFT', 6),
('Elle poste des photos de toi sans te demander', 20, 'NORMAL', 6),
('Il monopolise la télécommande toute la soirée', 20, 'NORMAL', 6),
('Elle commente tout ce que tu manges', 30, 'HARD', 6),
('Il est incapable de garder un secret', 30, 'HARD', 6),
('Elle dit "comme tu veux" mais veut clairement quelque chose', 30, 'HARD', 6),
('Il ne dit jamais merci', 20, 'NORMAL', 6),
('Elle te raconte ses rêves dans les moindres détails', 10, 'SOFT', 6),
('Il se plaint mais ne change rien', 30, 'HARD', 6),
('Elle double-dip dans les sauces communes', 20, 'NORMAL', 6),
('Il regarde son téléphone pendant que tu lui parles', 20, 'NORMAL', 6),
('Elle ne rappelle jamais quand elle rate un appel', 20, 'NORMAL', 6),
('Il prend 45 minutes aux toilettes chaque matin', 20, 'NORMAL', 6),
('Elle termine tes phrases, et pas toujours bien', 20, 'NORMAL', 6),
('Il compare toujours au moment d''acheter mais n''achète rien', 10, 'SOFT', 6),
('Elle met le chauffage à 30 degrés en hiver', 20, 'NORMAL', 6),
('Il ne consulte jamais les avis avant de choisir un restaurant', 10, 'SOFT', 6),
('Elle prend une heure à choisir au restaurant', 20, 'NORMAL', 6),
('Il oublie de fermer les placards', 10, 'SOFT', 6),
('Elle appelle "juste 5 minutes" et parle une heure', 20, 'NORMAL', 6),
('Il ne sait pas ce que "silencieux" veut dire', 20, 'NORMAL', 6),
('Elle répond "rien" quand tu demandes ce qu''elle veut manger', 30, 'HARD', 6),
('Il clique sur "rappeler plus tard" depuis 3 mois', 10, 'SOFT', 6),
('Elle ouvre 47 onglets et ne les ferme jamais', 10, 'SOFT', 6),
('Il demande son chemin mais n''écoute pas la réponse', 20, 'NORMAL', 6),
('Elle dit "je suis prête" mais met encore 20 minutes', 20, 'NORMAL', 6),
('Il parle la bouche pleine', 20, 'NORMAL', 6),
('Elle teste tes limites et fait l''innocente', 30, 'HARD', 6),
('Il ne lit jamais les modes d''emploi', 10, 'SOFT', 6),
('Elle répète la même histoire à chaque soirée', 20, 'NORMAL', 6),
('Il laisse des miettes partout', 10, 'SOFT', 6),
('Elle met du temps à répondre mais est en ligne', 30, 'HARD', 6),
('Il change les plans à la dernière minute', 30, 'HARD', 6),
('Elle commence à nettoyer quand tu t''installes confortablement', 20, 'NORMAL', 6),
('Il laisse le son de ses jeux vidéo à fond', 20, 'NORMAL', 6),
('Elle critique les films sans les avoir vus', 20, 'NORMAL', 6),
('Il met le réveil trop tôt et se rendort 47 fois', 20, 'NORMAL', 6),
('Elle analyse chaque message qu''elle reçoit pendant 2 heures', 30, 'HARD', 6),
('Il coupe la parole sans s''en rendre compte', 20, 'NORMAL', 6),
('Elle laisse toujours un tout petit peu de produit dans les flacons', 10, 'SOFT', 6),
('Il ne dit jamais "je ne sais pas" même quand il ne sait pas', 30, 'HARD', 6),
('Elle dit qu''elle n''est pas jalouse mais l''est clairement', 30, 'HARD', 6),
('Il met des heures à se décider pour une pizza', 10, 'SOFT', 6),
('Elle raconte la fin des films sans te demander si tu l''as vu', 30, 'HARD', 6),
('Il répond aux questions d''une seule syllabe', 20, 'NORMAL', 6),
('Elle dit toujours "je t''avais prévenu" après coup', 30, 'HARD', 6),
('Il mange ton dessert en pensant que tu n''en voulais plus', 20, 'NORMAL', 6),
('Elle organise tout mais ne délègue rien', 30, 'HARD', 6),
('Il accepte toutes les invitations et ne vient jamais', 20, 'NORMAL', 6),
('Elle fait la tête mais dit que tout va bien', 30, 'HARD', 6),
('Il répond "oui" à tout pour éviter les discussions', 20, 'NORMAL', 6),
('Elle demande ton avis mais a déjà décidé', 30, 'HARD', 6),
('Il ne sait pas ce que "on verra" veut dire', 20, 'NORMAL', 6),
('Elle trouve toujours un truc qui cloche dans les restos', 20, 'NORMAL', 6),
('Il dit "deux minutes" et revient 30 minutes plus tard', 10, 'SOFT', 6),
('Elle compare toujours avec son ex sans le faire exprès', 30, 'HARD', 6),
('Il souffle bruyamment quand il est énervé', 20, 'NORMAL', 6),
('Elle s''énerve puis fait comme si de rien n''était', 30, 'HARD', 6),
('Il mange debout devant le frigo ouvert', 10, 'SOFT', 6),
('Elle envoie des vocaux de 8 minutes', 20, 'NORMAL', 6),
('Il achète des trucs utiles et ne s''en sert jamais', 20, 'NORMAL', 6),
('Elle finit toujours les chips même quand elle "n''en voulait pas"', 20, 'NORMAL', 6),
('Il ne dit jamais "j''ai tort, pardon"', 30, 'HARD', 6),
('Elle change d''humeur aussi vite que la météo', 30, 'HARD', 6),
('Il perd ses clés minimum une fois par semaine', 10, 'SOFT', 6),
('Elle te demande ton avis sur sa tenue mais met ce qu''elle voulait', 20, 'NORMAL', 6),
('Il n''est jamais prêt quand tu le rejoins', 20, 'NORMAL', 6),
('Elle commence à ranger 5 minutes avant que les invités arrivent', 20, 'NORMAL', 6);

-- =============================================
-- CARTES — JEU 7 : Danse comme si...
-- =============================================
INSERT INTO card (question, points, level_card, game_id) VALUES
('Tu es un homme préhistorique pour Danse avec les Stars', 20, 'NORMAL', 7),
('Tu es une femme qui vient tout juste de rompre et qui va en boîte', 30, 'HARD', 7),
('Tu es une statue qui prend vie pour la première fois', 30, 'HARD', 7),
('Tu es un robot qui apprend la salsa', 20, 'NORMAL', 7),
('Tu es une grand-mère de 90 ans à un mariage', 10, 'SOFT', 7),
('Tu es un flamant rose au carnaval de Rio', 20, 'NORMAL', 7),
('Tu es un personnage de jeu vidéo des années 90', 20, 'NORMAL', 7),
('Tu es une star du disco qui ne sait plus comment on dansait', 20, 'NORMAL', 7),
('Tu es un cowboy texan dans une boîte de nuit parisienne', 20, 'NORMAL', 7),
('Tu es un militaire qui entend de la musique pour la première fois', 20, 'NORMAL', 7),
('Tu es une diva de l''opéra qui fait du hip-hop', 30, 'HARD', 7),
('Tu es une sirène qui essaie de danser sans queue de poisson', 30, 'HARD', 7),
('Tu es un super-héros qui a perdu ses pouvoirs', 20, 'NORMAL', 7),
('Tu es un chat qui imite son maître qui danse', 10, 'SOFT', 7),
('Tu es un mannequin qui défile sur une musique de boîte de nuit', 20, 'NORMAL', 7),
('Tu es une ballerine après 3 verres de champagne', 30, 'HARD', 7),
('Tu es un alien qui découvre la danse humaine', 20, 'NORMAL', 7),
('Tu es une reine d''Angleterre à un concert de rap', 20, 'NORMAL', 7),
('Tu es un chevalier en armure qui essaie de bouger', 30, 'HARD', 7),
('Tu es un pompier qui danse pour se réchauffer', 10, 'SOFT', 7),
('Tu es une personne qui entend de la musique que personne d''autre n''entend', 30, 'HARD', 7),
('Tu es une star de yoga qui entend du métal pour la première fois', 30, 'HARD', 7),
('Tu es une personne dont les chaussures sont trop petites', 20, 'NORMAL', 7),
('Tu es un pingouin qui gagne un concours de danse', 20, 'NORMAL', 7),
('Tu es une mariée qui danse sur la chanson de mariage de son ex', 30, 'HARD', 7),
('Tu es un DJ qui fait semblant que sa sono est en panne', 20, 'NORMAL', 7),
('Tu es un lutteur de sumo à la soirée dansante de son enterrement de vie de garçon', 20, 'NORMAL', 7),
('Tu es une gymnaste qui interprète une chanson d''amour', 20, 'NORMAL', 7),
('Tu es un chef cuisinier qui danse en préparant un plat', 10, 'SOFT', 7),
('Tu es une personne qui danse sous la pluie et fait semblant que c''est romantique', 20, 'NORMAL', 7),
('Tu es un clown triste lors d''une fête d''anniversaire', 20, 'NORMAL', 7),
('Tu es un pompier qui danse dans une discothèque en feu', 30, 'HARD', 7),
('Tu es un bébé qui vient d''apprendre à marcher et qui veut danser', 10, 'SOFT', 7),
('Tu es une star de cinéma qui accepte un rôle de danseur classique', 30, 'HARD', 7),
('Tu es un politicien qui danse pour gagner des votes', 20, 'NORMAL', 7),
('Tu es un pirate sur un bateau en pleine tempête', 20, 'NORMAL', 7),
('Tu es une princesse de Disney au milieu d''un concert de hard rock', 30, 'HARD', 7),
('Tu es un astronaute qui revient sur Terre après 6 mois', 20, 'NORMAL', 7),
('Tu es un paysan médiéval qui découvre la musique électronique', 20, 'NORMAL', 7),
('Tu es une cheerleader dont les pompons sont en feu', 30, 'HARD', 7),
('Tu es un ninja qui essaie d''être discret sur la piste de danse', 30, 'HARD', 7),
('Tu es une personne qui essaie de danser sans bouger les hanches', 20, 'NORMAL', 7),
('Tu es un touriste qui imite les danses locales sans les connaître', 10, 'SOFT', 7),
('Tu es une pop star dont le playback se détraque', 30, 'HARD', 7),
('Tu es un zombie qui retrouve le goût de la danse', 20, 'NORMAL', 7),
('Tu es un directeur d''école qui danse pour punir ses élèves', 20, 'NORMAL', 7),
('Tu es un personnage de film d''horreur qui danse', 30, 'HARD', 7),
('Tu es une personne qui a les mains dans les poches et essaie de danser', 10, 'SOFT', 7),
('Tu es un danseur de flamenco qui entend du reggaeton', 20, 'NORMAL', 7),
('Tu es un médecin urgentiste qui danse entre deux opérations', 30, 'HARD', 7),
('Tu es une personne qui danse sur du jazz mais en croyant que c''est du rap', 20, 'NORMAL', 7),
('Tu es une star de K-pop qui danse un slow de mariage', 20, 'NORMAL', 7),
('Tu es un moniteur de ski qui fait du breakdance', 20, 'NORMAL', 7),
('Tu es un fantôme qui essaie de faire peur en dansant', 20, 'NORMAL', 7),
('Tu es une personne en scaphandre qui danse la lambada', 30, 'HARD', 7),
('Tu es un sosie de star qui danse mais avec 10 ans de retard', 20, 'NORMAL', 7),
('Tu es un prof de gym à la retraite qui revient sur la piste', 10, 'SOFT', 7),
('Tu es une personne qui danse et dont la perruque glisse', 20, 'NORMAL', 7),
('Tu es un chanteur d''opéra qui fait du moonwalk', 30, 'HARD', 7),
('Tu es une personne qui découvre qu''elle a les jambes en coton après 3 shots', 20, 'NORMAL', 7),
('Tu es un détective privé qui surveille quelqu''un sur la piste de danse', 30, 'HARD', 7),
('Tu es un bodybuilder qui essaie de danser la valse', 20, 'NORMAL', 7),
('Tu es un enfant de 5 ans qui imite ses parents sur la piste', 10, 'SOFT', 7),
('Tu es une personne qui danse en imaginant être dans un clip vidéo', 20, 'NORMAL', 7),
('Tu es un pêcheur qui applique ses gestes de pêche à la danse', 20, 'NORMAL', 7),
('Tu es une personne avec un ballon coincé entre les genoux', 30, 'HARD', 7),
('Tu es un chef d''orchestre qui perd le contrôle de ses musiciens', 30, 'HARD', 7),
('Tu es une personne qui danse et dont les chaussures se détachent', 10, 'SOFT', 7),
('Tu es un surfeur qui applique ses moves de surf à la danse', 20, 'NORMAL', 7),
('Tu es une personne qui danse et qui réalise qu''elle est filmée', 20, 'NORMAL', 7),
('Tu es un Viking qui découvre la techno', 20, 'NORMAL', 7),
('Tu es une personne qui danse avec ses animaux de compagnie imaginaires', 20, 'NORMAL', 7),
('Tu es un soldat qui danse pour fêter la paix', 20, 'NORMAL', 7),
('Tu es un marin en pleine mer qui essaie de danser', 20, 'NORMAL', 7),
('Tu es une personne âgée qui retrouve ses mouvements de jeunesse', 10, 'SOFT', 7),
('Tu es un DJ que personne ne regarde et qui s''ennuie', 20, 'NORMAL', 7),
('Tu es une personne qui danse et dont le téléphone sonne', 10, 'SOFT', 7),
('Tu es une célébrité qui danse incognito dans un festival', 20, 'NORMAL', 7),
('Tu es un acteur qui joue le rôle d''un danseur mais qui ne sait pas danser', 30, 'HARD', 7),
('Tu es une personne qui danse les bras en l''air sous une douche froide', 30, 'HARD', 7),
('Tu es un comptable qui se lâche pour la première fois de sa vie', 20, 'NORMAL', 7),
('Tu es un moine bouddhiste qui entend du techno', 30, 'HARD', 7),
('Tu es une personne qui danse et qui a un deuxième souffle après avoir cru être épuisée', 20, 'NORMAL', 7),
('Tu es un moniteur de plongée qui danse sous l''eau', 20, 'NORMAL', 7),
('Tu es une personne qui imite exactement les mouvements de la personne en face d''elle', 10, 'SOFT', 7),
('Tu es un vendeur de glaces qui danse pour attirer les clients', 10, 'SOFT', 7),
('Tu es une personne qui danse comme si elle gagnait un Oscar', 20, 'NORMAL', 7),
('Tu es un pompier qui fait du hip-hop pendant qu''il éteint un incendie', 30, 'HARD', 7),
('Tu es une personne qui danse et dont le costume de soirée se déchire', 30, 'HARD', 7),
('Tu es un médecin légiste qui danse pour se changer les idées', 30, 'HARD', 7),
('Tu es une personne en train de danser qui réalise qu''elle est seule sur la piste', 20, 'NORMAL', 7),
('Tu es un prof de danse classique dont l''élève fait tout à l''envers', 20, 'NORMAL', 7),
('Tu es une personne qui danse et qui perd sa chaussure comme Cendrillon', 20, 'NORMAL', 7),
('Tu es une personne qui interprète le générique de sa série préférée', 10, 'SOFT', 7),
('Tu es un plombier qui applique ses gestes de boulot à la danse', 20, 'NORMAL', 7),
('Tu es une personne qui danse pour célébrer une promotion au travail', 10, 'SOFT', 7),
('Tu es un cosmonaute qui danse en apesanteur', 30, 'HARD', 7);